SylteA/Discord-Bot

- README.md
> Join our server

- votes.py
Duplicated add_vote and changed some bits.
Remove_vote would allow the user to remove their vote from the database.
> remove_vote

- log.py
Removed old poll system.
Changed prefix.
Added new poll system.
> New Poll System!

- main.py
Havent had time for any testing yet, need some sleep first
> Temporary fix

- cogs/tags.py
- cogs/utils/DataBase/tag.py
- cogs/utils/checks.py
Please test before putting onto the main bot.
> Make tag commands

- cogs/commands.py
Pull request submitted to testing branch
> Added PyGame to available documents

- cogs/challenges.py
Alanhong reported a bug where if you react to the challenge again, you can submit one more time. That has to do with the role permissions, and this should fix it.
> check for submitted role before adding participant

- cogs/tags.py
- cogs/utils/checks.py
Added engineer check and used that check for the tag commands
> Engineers are able to create edit delete and list tags

- cogs/challenges.py
when someone answer in solution channel it delete it and resend it in a submissions channel which only who submitted can see it
p.s:  it should be submitted people can't see solution channel and participant people can't see submission channel
> a better way for submitting

- cogs/clashofcode.py
> Update coc regex

- cogs/commands.py
- cogs/tags.py
- requirements.txt
Command to be able to search through the pip packages for python in pypi.org. Gives link, latest version, and short description.
> Pypi.org search and tag commands

- cogs/commands.py
Code by Biz but he was too lazy to do it ~takos + 12944qwerty's change to no result found message.
Hope that did it correctly as it's my first ever PR
> Corrected pip command

- cogs/commands.py
- cogs/tags.py
t.tag all send all tags as DM (takos PR + 1 day cooldown per user)
> Bring t.tag all back(DM version)

- cogs/commands.py
> fixing pip command

- cogs/challenges.py
- cogs/tags.py
- cogs/utils/DataBase/tag.py
better then deleting and creating a new one :/
> tag rename command

- cogs/challenges.py
Automatically add a reaction to the challenge/code jam
> Automatic reaction for the challenges

- cogs/tags.py
Idk why the code before didn’t work but I tried to fix it
> Fix not found tag message deletion

- cogs/commands.py
"Showing {amount}/{results} results." instead of "Showing 10/{results} results.". To make it work with custom amount of searches
> Update pipsearch command

- cogs/challenges.py
Updated Monthly Challenge to make it give the submitted role to the whole team in the monthly code jam
> Updated Monthly Challenge

- cogs/clashofcode.py
- cogs/utils/context.py
- main.py
> Whoops again 

- cogs/roles.py
Change on_reaction events to on_raw_reaction
> Fix roles.py

- cogs/moderation.py
I can fix other people’s bugs but I can’t find mine :mhm:
> Bug fix in report

- cogs/commands.py
command name +url can be over 100 chars that is y
> fixing source command

- .vscode/settings.json
- cogs/commands.py
Usage 
-Correct_skill
Command to give poll results
> Added command poll results

- cogs/challenges.py
if it was a bot it deletes the msg and do nothing
> simple fix on challenges

- cogs/commands.py
Update the reps command to show people who repped :)
> Update reps command

- cogs/utils/context.py
~~now only sylte can do it through jsk~~
~~MUAHAHAHAAHHA~~
> no more cheating to get help in wrong channels

- cogs/clashofcode.py
- cogs/moderation.py
- cogs/poll.py
I can't test that much alone :smilecat:
> fixed silly errors

- cogs/tags.py
My first contribution :>
So basically, when I create tag myself, I sometimes mis-click enter instead of shift answer. Therefore, I have to copy & paste all stuff again and that is wasting my time.
So I made an append function. This function takes same ares as edit, but it adds A SPACE and then the second arg to the first arg (tag). Just some simple stuff, hope it got approved hehe 😄
> tag append

- README.md
> Update to vanity url

- cogs/verify.py
> spelling error

- main.py
Add a channel mention in "Please use the #bot-commands channel"
> #bot-commands channel mention

- cogs/challenges.py
Changing the way of submitting from code block to attaching a file.
> Change way of submitting in weekly challenges.

- main.py
This is just another pull request with the changes asked in #145 as i deleted that fork thinking that it'll never be merged as it has been there for months. So, I can no longer make edits to that.
> Disabling Bot Commands in Submit Channels

- cogs/tags.py
- cogs/utils/checks.py
allow all staff to delete tags instead of only admins
> change tag delete perms to all staff

- cogs/commands.py
In commands.py line 378 under the suggest method, I changed `Poll by` to `Suggestion by` as it is for suggestion and not a poll. This has been bugging me for some days so decided to fix it
> Changed "Poll by" to "Suggestion by"

- cogs/_help.py
- cogs/adventofcode.py
- cogs/challenges.py
- cogs/clashofcode.py
- cogs/commands.py
- cogs/filtering.py
- cogs/poll.py
- cogs/roles.py
- cogs/tags.py
- cogs/utils/DataBase/client.py
- cogs/utils/context.py
- cogs/youtube.py
- config.py
- example.env
- main.py
- requirements.txt
- Account for the breaking changes
- Use the bot instead of a webhook for sending tag requests
- Replace prints with logging (Unused cogs not included)
> Migrate discord.py to v2

- bot/extensions/challenges/events.py
Gives user Participant instead of Submitted role on Reaction
> Challenge - Give user Participant instead of Submitted role on Reaction

- bot/config.py
- bot/core.py
- bot/services/paste.py
Introduces 2 new env vars, @mohamed040406 please add them to the deployment I will send them in dms
> Add some basic error handling

- bot/extensions/challenges/events.py
Should identify if the user is a bot and, if so, avoid adding a role to one. Feedback is welcome
> Update events.py to check if the user is a bot

- bot/models/migrations/migration.py
- cli.py
fixes #234 
Screenshot of how it looks on running migrate command now 
first line is ```current migrations: ```not ```current migrate:```
> migrate command shows if there are available migrations
